### ISSUE TITLE
isCaching incorrectly set

### ISSUE THREAD

**Issue by rabidgremlin** [furkleindustries/inklecate-node#2]
Hiya,

The `isCaching` flag in `inklecate.js` appears to be set incorrectly to `true` causing the `outputFilepath` to be ignored and the compiled Ink file to be placed in a cache location.

If I run this command
```
inklecate --DEBUG -o D:\\working\\ozy\\dist\\main.ink.json --verbose  ink/main.ink
```

Then no output file is created. Following output is generated in console:
```
inklecate-node is using an executable inklecate. {
  countAllVisits: false,
  inputFilepath: 'ink\\main.ink',
  isCaching: true,
  outputFilepath: 'D:\\working\\ozy\\node_modules\\inklecate\\cache\\60ee4952-32a8-5875-9f69-71edd4028ab7.json',
  verbose: true,
  DEBUG: true
}
```

If I add additionally logging to `inklecate.js` as follows:
```
  const countAllVisits = Boolean(args.countAllVisits);

  console.log("OPB:", args.outputFilepath);

  const outputFilepath = args.outputFilepath ?
    relative(process.cwd(), args.outputFilepath) :
    null;

  console.log("OPF:", outputFilepath);  

  const isCaching = Boolean(outputFilepath); 
```

I get the following output
```
OPB: D:\working\ozy\dist\main.ink.json
OPF: dist\main.ink.json
```

Which is correct BUT the `isCaching` flag is still set to true which is not correct.

I believe the fix is to negate the boolean that creates the isCaching const. Eg:
```
const isCaching = !Boolean(outputFilepath); 
```
As we DON'T want to cache if an outputfile is specified

**Comment by furkle** [comment]
aha! thank you so much for reporting this. i believe there's a fallback i was probably making use of, in which it defaults to `isCaching`. i'll update this right now.

**Comment by furkle** [comment]
this fix should be live for both this and https://github.com/furkleindustries/inklecate-loader.

thanks again for the help. clearly my integration tests, which make use of the underlying and generic functions, not the CLI, need to be expanded to cover CLI args and logic. i'll put it on my list!

**Comment by rabidgremlin** [comment]
`1.7.2` is working for me. Thanks for the fix.
