### ISSUE TITLE
inklecate.js file have some issue

### ISSUE THREAD

**Issue by Vikas730** [furkleindustries/inklecate-node#9]
Hi there,

I have set up and configured this repository but unfortunately I didn't get any response with this.
I have followed your given steps i.e. "how to use" but it didn't seems to be working when I was trying to run a command like "inklecate -c"  in my command prompt then it was open "inklecate.js" file in my editor and showing error on line 2, I have set up the module path here but it gave me same issue on running any command given by you can you please help me.

Thanks in advanced!

**Comment by furkle** [comment]
sorry, i've been away from this project for awhile! am i understanding correctly that you're trying to globally install this package?
